Programing_Phoenix/rumbl/lib/rumbl_web/router.ex
defmodule RumblWeb.Router do
  use RumblWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RumblWeb.Auth, repo: Rumbl.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RumblWeb do
    pipe_through :browser
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    get "/", PageController, :index
    get "/watch/:id", WatchController, :show
  end

  scope "/manage", RumblWeb do
    pipe_through [:browser, :authenticate_user]
    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", RumblWeb do
  #   pipe_through :api
  # end
end

Programing_Phoenix/rumbl/lib/rumbl_web/controllers/session_controller.ex
defmodule RumblWeb.SessionController do
  use RumblWeb, :controller

  def new(conn, _) do
    render(conn, "new.html")
  end

  def create(conn, %{"session" => %{"username" => user, "password" => pass}}) do
    case RumblWeb.Auth.login_by_username_and_pass(conn, user, pass, repo: Rumbl.Repo) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: page_path(conn, :index))

      {:error, _reason, conn} ->
        conn
        |> put_flash(:error, "Invalid username/password combination")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> RumblWeb.Auth.logout()
    |> redirect(to: page_path(conn, :index))
  end

end

Programing_Phoenix/rumbl/lib/rumbl_web/views/session_view.ex
defmodule RumblWeb.SessionView do
  use RumblWeb, :view
end

Programing_Phoenix/rumbl/lib/rumbl_web/templates/session/new.html.eex
<h1>Login</h1>
<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %> 
    <div class="form-group">
        <%= text_input f, :username, placeholder: "Username", class: "form-control" %> 
    </div>
    <div class="form-group">
        <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
    </div>
    <%= submit "Log in", class: "btn btn-primary" %> 
<% end %>