Programing_Phoenix/rumbl/lib/rumbl_web/router.ex
defmodule RumblWeb.Router do
  use RumblWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RumblWeb.Auth, repo: Rumbl.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RumblWeb do
    pipe_through :browser
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    get "/", PageController, :index
    get "/watch/:id", WatchController, :show
  end

  scope "/manage", RumblWeb do
    pipe_through [:browser, :authenticate_user]
    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", RumblWeb do
  #   pipe_through :api
  # end
end

Programing_Phoenix/rumbl/lib/rumbl_web/controllers/video_controller.ex
defmodule RumblWeb.VideoController do
  use RumblWeb, :controller

  alias Rumbl.Repo
  alias RumblWeb.Video
  alias RumblWeb.Category

  plug :load_categories when action in [:new, :create, :edit, :update]


  def action(conn, _) do
    apply(__MODULE__, action_name(conn), [conn, conn.params, conn.assigns.current_user])
  end

  def index(conn, _params, user) do
    videos = Repo.all(user_videos(user))
    render(conn, "index.html", videos: videos)
  end

  def new(conn, _params, user) do
    changeset =
      user
      |> build_assoc(:videos)
      |> Video.changeset()

    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"video" => video_params}, user) do
    changeset =
      user
      |> build_assoc(:videos)
      |> Video.changeset(video_params)

    case Repo.insert(changeset) do
      {:ok, _video} ->
        conn
        |> put_flash(:info, "Video created successfully.")
        |> redirect(to: video_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}, user) do
    video = Repo.get!(user_videos(user), id)
    render(conn, "show.html", video: video)
  end

  # def edit(conn, %{"id" => id}, user) do
  #   video = Repo.get!(user_videos(user), id)
  #   changeset = Video.changeset(video)
  #   render(conn, "edit.html", video: video, changeset: changeset)
  # end

  def edit(conn, %{"id" => id}, user) do
    IO.puts "edit"
    video = Repo.get!(user_videos(user), id)
    changeset = Video.changeset(video)
    render(conn, "edit.html", video: video, changeset: changeset)
  end

  def update(conn, %{"id" => id, "video" => video_params}, user) do
    video = Repo.get!(user_videos(user), id)
    changeset = Video.changeset(video, video_params)
    IO.puts "udapte"
    case Repo.update(changeset) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video updated successfully.")
        |> redirect(to: video_path(conn, :show, video))
      {:error, changeset} ->
        render(conn, "edit.html", video: video, changeset: changeset)
    end
  end

  # def update(conn, %{"id" => id, "video" => video_params}, user) do
  #   video = Repo.get!(user_videos(user), id)
  #   changeset = Video.changeset(video, video_params)

  #   case Repo.update(changeset) do
  #     {:ok, video} ->
  #       conn
  #       |> put_flash(:info, "Video updated successfully.")
  #       |> redirect(to: Routes.video_path(conn, :show, video))

  #     {:error, %Ecto.Changeset{} = changeset} ->
  #       render(conn, "edit.html", video: video, changeset: changeset)
  #   end
  # end

  def delete(conn, %{"id" => id}, user) do
    video = Repo.get!(user_videos(user), id)
    Repo.delete!(video)

    conn
    |> put_flash(:info, "Video deleted successfully.")
    |> redirect(to: Routes.video_path(conn, :index))
  end

  defp user_videos(user), do: assoc(user, :videos)

  defp load_categories(conn, _) do
    query =
      Category
      |> Category.alphabetical()
      |> Category.names_and_ids()

    categories = Repo.all(query)
    assign(conn, :categories, categories)
  end


end

Programing_Phoenix/rumbl/lib/rumbl_web/views/video_view.ex
defmodule RumblWeb.VideoView do
  use RumblWeb, :view
end

Programing_Phoenix/rumbl/lib/rumbl_web/templates/video/edit.html.eex
<h1>Edit Video</h1>

<%= render "form.html", changeset: @changeset, categories: @categories, action: video_path(@conn, :update, @video) %> 

<%= link "Back", to: video_path(@conn, :index) %>

Programing_Phoenix/rumbl/lib/rumbl_web/templates/video/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :url %>
  <%= text_input f, :url %>
  <%= error_tag f, :url %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :description %>
  <%= textarea f, :description %>
  <%= error_tag f, :description %>

  <div class="form-group">
    <%= label f, :category_id, "Category", class: "control-label" %> 
    <%= select f, :category_id, @categories, class: "form-control", prompt: "Choose a category" %>
  </div>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

Programing_Phoenix/rumbl/lib/rumbl_web/templates/video/index.html.eex
<h1>Listing Videos</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Title</th>
      <th>Description</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for video <- @videos do %>
    <tr>
      <td><%= video.url %></td>
      <td><%= video.title %></td>
      <td><%= video.description %></td>

      <td>
        <%= link "Watch", to: Routes.watch_path(@conn, :show, video), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: Routes.video_path(@conn, :edit, video) %>
        <%= link "Delete", to: Routes.video_path(@conn, :delete, video), method: :delete, data: [confirm: "Are you sure?"] %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Video", to: Routes.video_path(@conn, :new) %></span>

Programing_Phoenix/rumbl/lib/rumbl_web/templates/video/new.html.eex
<h1>New Video</h1>

<%= render "form.html", changeset: @changeset, categories: @categories, action: video_path(@conn, :create) %> 

<%= link "Back", to: video_path(@conn, :index) %>

Programing_Phoenix/rumbl/lib/rumbl_web/templates/video/show.html.eex
<h1>Show Video</h1>

<ul>

  <li>
    <strong>Url:</strong>
    <%= @video.url %>
  </li>

  <li>
    <strong>Title:</strong>
    <%= @video.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @video.description %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.video_path(@conn, :edit, @video) %></span>
<span><%= link "Back", to: Routes.video_path(@conn, :index) %></span>